### ISSUE TITLE
Recording source and redirect user when they type the input by themselves

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-line-bot#121]
Discussions:
- https://g0v.hackmd.io/s/SyN-sb8b4#%E6%94%B6%E9%80%B2%E4%BE%86%E7%9A%84%E8%A8%8A%E6%81%AF%E4%B8%8D%E6%98%AF%E8%BD%89%E5%82%B3%E8%A8%8A%E6%81%AF

「請問您是從哪裡看到這則訊息的」
- 「親戚轉傳」
- 「同事轉傳」
- 「朋友轉傳」
- 「自己輸入的」

**Comment by changhc** [comment]
I'm fixing the missed part that the bot should also ask the source of incoming articles when a user selects "這裡沒有一篇是我傳的文章".

**Comment by MrOrz** [comment]
突然覺得比較有意義的分類會是
- 自己輸入 / LINE 之外的訊息
- 家族 LINE 群
- 宗教（禪修、教堂）LINE 群
- 地方 LINE 群
- 公共議題 LINE 群
- LINE 官方帳號
- LINE 私訊
- 其他 LINE 群組

**Comment by changhc** [comment]
這樣按鈕會太多吧，而且好像不是 mutually exclusive

**Comment by MrOrz** [comment]
我也覺得有點多 QQ 這可以週三開會討論一下。

不過我觀察到的群組應該都只會符合一個分類？

**Comment by MrOrz** [comment]
Follow-ups should go to #145 , closing this issue since its PR is merged.
