### ISSUE TITLE
支援 LINE chatbot 群組聊天

### ISSUE THREAD

**Issue by godgunman** [cofacts/rumors-line-bot#13]
LINE Bot 再被加進去群組之後，把在群組裡面的訊息，拿去對前 100 則查證的訊息做 in-memory 的查詢（#14）。

Related discussion:
20170318 - https://beta.hackfoldr.org/cofacts/https%253A%252F%252Fhackmd.io%252Fs%252FrJ0nBnYsx

**Comment by MrOrz** [comment]
From: http://beta.hackfoldr.org/cofacts/https%253A%252F%252Fhackmd.io%252Fs%252FBJRJxopTb

GGM:
之前比較麻煩要 cache top 100，但我覺得

1. 回應超過 50 個字的。正常講話不會超過 50 個字
2. 搜尋後相似度 80% 以上的才回傳

這樣似乎也 OK。

**Comment by MrOrz** [comment]
[20201104 Discussion](https://g0v.hackmd.io/Sl_84QO8TQ6WKKI0bT4pYw#TODO):

- 目的
    - 建立「Cofacts 會如何在群組裡對話」的示範
    - more *accurate* view count
- 功能
    - 還是會在群組裡自動回話，但只限於：
        - 訊息相似度幾乎完全命中
        - Category: 醫藥保健、COVID-19、資訊安全
        - 狀態：has useful reply 且標為「含有錯誤訊息」、「含有個人意見」 
            > 過去收到的 feedback 是在群組裡回話會中斷討論流程，尤其是「不在查證範圍」
    - 針對群組內「已經有人回報」的訊息 (不限於會自動回話的)：
        - 送 google analytics viewed 數
            - 若群組內有 5 人，一次要加幾個 view count？
                - 算是一個人、一次 view count [name=bil]
            - view 過 article 不代表有 view 過 reply
                - 還是算一次 view article [name=bil]
        - 自動送出 reply request (?)
            - 在群組裡被送入，不要送 reply request，因為這與「發問」不同 [name=bil]
            - 增加 google analytics count 就好 [name=bil] 
        - 幫群組裡有加 cofacts 的人建立 `userArticleLink`
            - 放的話他可以收到新回應推播 [name=mrorz]
            - 「看過的訊息」是私人的體驗，放了會有點破壞。先不要 [name=bil]
- 先不要功能
    - 私訊群組裡有加 cofacts 的人
    - [原始提案](https://g0v.hackmd.io/-j-fAX0tS62amv9LejshOg#%E7%BE%A4%E7%B5%84%E8%A8%8A%E6%81%AF)中的「hash 保存」
- 技術
    - Job queue (open-source 版美玉姨的做法)
        - delay: reply token 到期之前能回就好
- 材料
    - 自介 wording
        - 被 tag 時再自我介紹即可
    - 回應時的 wording
    - ＦＡＱ：隱私疑慮、bot 誰做的、跟美玉姨的差別
        - 放主頁置頂即可
