### ISSUE TITLE
Cron job that renews LINE OA token

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-line-bot#136]
Currently the channel token will expire in 30 days.

We must add a cron job to refresh the channel token

**Comment by nonumpa** [comment]
ref:https://developers.line.biz/en/reference/messaging-api/#issue-channel-access-token

**Comment by MrOrz** [comment]
Implemented in https://github.com/cofacts/rumors-deploy/pull/11 and it's now in place. Kudos to @nonumpa !
