### ISSUE TITLE
LIFF trap source should guide user to other fact checkers

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-line-bot#190]
Response is now incorrect.

According to [source code](https://github.com/cofacts/rumors-line-bot/blob/dev/src/webhook/handlers/askingArticleSubmissionConsent.js#L35-L41), it should block article submission and shows hint to other fact checkers (see [unit test](https://github.com/cofacts/rumors-line-bot/blob/dev/src/webhook/handlers/__tests__/askingArticleSubmissionConsent.test.js#L57-L84
))

Instead, it shows:
![Screenshot_20200520-203235](https://user-images.githubusercontent.com/108608/82446786-e2179b00-9ad9-11ea-8986-4c361d0c86e1.png)

**Comment by nonumpa** [comment]
It's not a bug.
This case is `ASKING_REPLY_REQUEST_REASON` state that means the article was already submitted.

**Comment by MrOrz** [comment]
I see, in that case the trap options like "我在 LINE 外頭看到的" should be hidden from the LIFF.

If we can ensure the trap options are hidden, we can close the issue.

**Comment by MrOrz** [comment]
As discussed on Slack in 7/22 we plan to remove the step that asks source. Closing this issue.
