### ISSUE TITLE
Error: user doesn't grant required permissions yet

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-line-bot#191]
View details in Rollbar: [https://rollbar.com/mrorz/rumors-line-bot/items/216/](https://rollbar.com/mrorz/rumors-line-bot/items/216/)

```

Error: user doesn't grant required permissions yet
  File "https://static.line-scdn.net/liff/edge/2.1/sdk.js", line 2, in t
  File "https://static.line-scdn.net/liff/edge/2.1/sdk.js", line 2, in z
  File "https://static.line-scdn.net/liff/edge/2.1/sdk.js", line 2, in [anonymous]
  File "https://static.line-scdn.net/liff/edge/2.1/sdk.js", line 2, in [anonymous]
  File "https://static.line-scdn.net/liff/edge/2.1/sdk.js", line 2, in s
  File "[native code]", line unknown, in promiseReactionJob
```

**Comment by MrOrz** [comment]
I suspect this is because the user removed "send message to chatroom" function.

Need help reproducing this bug. If this is confirmed, we should come up with a way to aid user enable the permission.

**Comment by nonumpa** [comment]
After testing, this error message only appears on iOS when user doesn't allow `send messages to chat` permission but still try to trigger a button that will call `liff.sendMessages`.

<img src="https://user-images.githubusercontent.com/6376572/87516185-91728780-c6af-11ea-9c82-882818dc3017.png" width="250">

Although Line will always ask for permission every time liff opening if user didn't grant,
for better user experience, we should handle [LiffError](https://developers.line.biz/en/reference/liff/#return-value-19) returns from `liff.sendMessages`.

**Comment by MrOrz** [comment]
I have a bold idea.

When we catch `liffError`, we can explain that we need "Send messages to chats" just because we want to send message back to Cofacts, then provide a button that reads  "Go back and click 'send' by myself".

The button is actually a link to a LINE URL scheme that [sends text to an official account](https://developers.line.biz/en/docs/line-login/using-line-url-scheme/#sending-text-messages), in this case, `@cofacts`. 

Then we can put the text previously in `sendMessage()` into the URL scheme, so that when the user clicks the button, the URL scheme will bring them back to `@cofacts` chat screen, with message to send inside their text dialog. When the user clicks "send" button, the chatbot receives the message (prefixed with LIFF prefixes), and then proceed the steps.
