### ISSUE TITLE
有些長文章可能有特殊字元，會讓 LINE bot 會已讀不回

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-line-bot#2]
![2017-03-04 10 16 16](https://cloud.githubusercontent.com/assets/108608/23575170/e2616eb4-00c3-11e7-9f52-b4708632f129.png)

但在電腦上複製文字、貼上給 line bot，LINE bot 又會回了 @@

**Comment by godgunman** [comment]
晚十二點是女鬼的生日，收到晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的晚晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的晚晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的晚晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的晚晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下晚十二點是女鬼的生日，收到此信息者傳給看完 不傳者：今晚一點會在床邊看著你喔。今晚會在 天板上看著你喔，還會一直叫著你的名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下名字！ 1994年6月29號，某人因把這封信刪除，第二天 他突然死亡，被人發他的屍體，如果你把這封信 刪除的話，你的家人會在5天內死亡。如果你在 看這封信的24小時內，傳給20個人，你家不會 鬧鬼。把這封信發給你的20個朋友，10天后， 你喜歡的人就會喜歡上你。如果不發，你媽媽很 快被車撞死（很靈）不知道誰傳的，我也是被逼 對不起
願望信
天神們又開始傳福了

傳1人～幸運半小時
傳2人～幸運一小時😇
傳3人～幸運半天😎
傳4人～全天幸運
傳5人～一星期內你的愛人開始留意妳
傳6人～朋友更多👬👭
傳7人～一星期快樂😙
傳8人～人氣急性
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下
傳9人～你愛的人已迷上了妳
傳10人～1-9全有

不信就試一下

**Comment by godgunman** [comment]
發現又無法重現 bug 了，哭哭

**Comment by MrOrz** [comment]
Cannot reproduce, close for now
