### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by nonumpa** [cofacts/rumors-line-bot#220]
### An article matches but there's no highlight
Should take a look at cofacts-api to see why it matches.

![](https://user-images.githubusercontent.com/6376572/93561350-95c06700-f9b6-11ea-90aa-0595cf65aabd.png)

View details in Rollbar: [https://rollbar.com/mrorz/rumors-line-bot/items/283/](https://rollbar.com/mrorz/rumors-line-bot/items/283/)

```

TypeError: Cannot read property 'split' of undefined
  File "/app/build/webhook/handlers/utils.js", line 438, in createHighlightContents
      for (let highlightPair of text.split('</HIGHLIGHT>')) {
  File "/app/build/webhook/handlers/initState.js", line 217, in <unknown>
            contents: (0, _utils.createHighlightContents)(highlight, text),
  File "<anonymous>", line unknown, in Array.map
  File "/app/build/webhook/handlers/initState.js", line 192, in initState
        const articleOptions = edgesSortedWithSimilarity.map(({
  File "<anonymous>", line unknown, in runMicrotasks
  File "internal/process/task_queues.js", line 97, in processTicksAndRejections
  File "/app/build/webhook/handleInput.js", line 96, in async handleInput
                params = await (0, _initState.default)(params);
  File "/app/build/webhook/index.js", line 210, in async processText
        result = await (0, _handleInput.default)(context, {
  File "/app/build/webhook/index.js", line 128, in async singleUserHandler
        result = await processText(context, type, input, otherFields, userId, req);
```

**Comment by MrOrz** [comment]
Another instance is reported today
```
刷樂，依必朗，3M漱口水有含那成份Chlorhexidine
https://www.worldjournal.com/wj/story/121471/5394313?fbclid=IwAR1HowY-Wq-5szf51JMVqrkN5tM053M9-qCtEEjj-bSiIXT2JBGH7H9Ea
```
![image](https://user-images.githubusercontent.com/108608/118162903-e4de6f00-b453-11eb-974c-b9a473b2ebaf.png)
![image](https://user-images.githubusercontent.com/108608/118163066-1e16df00-b454-11eb-9c8f-e239744c91f6.png)


Its variant will not trigger such error.

No fbclid --> OK
![image](https://user-images.githubusercontent.com/108608/118162947-f0319a80-b453-11eb-83c0-56e32ff67f35.png)

URL only with fbclid --> OK
![image](https://user-images.githubusercontent.com/108608/118162983-fb84c600-b453-11eb-934e-f1538aaa7407.png)

Text only ---> OK
![image](https://user-images.githubusercontent.com/108608/118163007-05a6c480-b454-11eb-853e-d117c18c6a39.png)

**Comment by nonumpa** [comment]
Two more cases:
```
"6/18
立法院實錄~
民進黨立委於立法院否決4000萬劑進口國際認疫苗的法案！全民（包括1450+817）如何看這個黨？https://youtu.be/nSbLL5ZtDbo
```
```
小心囉，北農18名新冠確診，四樓營業部重災區，每天包20-30萬包蔬菜給全聯，前幾天就有了，但因為蔬果是民生必需品，故沒公佈，今天爆18人，大概是瞞不住了，暫時不要去全聯！

https://udn.com/news/story/120940/5537424?from=udnamp_storysns_line
```
