### ISSUE TITLE
"must not be longer than 120 characters" error

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-line-bot#23]
Reported from FB group:
https://www.facebook.com/groups/cofacts/permalink/1987269594838193/
https://www.facebook.com/groups/cofacts/permalink/2003548476543638/

@godgunman  @darkbtf please see if Botimize log contains the reported message.

Relevant Rollbar error log:
- https://rollbar.com/mrorz/rumors-line-bot/items/36/occurrences/26815441841/
- https://rollbar.com/mrorz/rumors-line-bot/items/36/occurrences/26815813877/
- https://rollbar.com/mrorz/rumors-line-bot/items/36/occurrences/29113740060/

Furthermore, I think we should consider a better solution in controlling string lengths.
Relevant discussions on solutions in character length control: https://g0v-tw.slackarchive.io/cofacts/page-8/ts-1497460109184405

**Comment by MrOrz** [comment]
Got an example here:
```
 這樣的大事國內媒體竟然不敢報導！
我國駐日代表將原「中華民國」申請更名為「台灣」結果被日本裁罰，須繳納7000萬日圓（合約台幣2100萬元）高額稅賦(轉載中時電子報）

我駐日代表謝長廷將原「中華民國」申請更名為「台灣」，自認得意之時，結果遭自認友好日本國給出賣了，必須繳納7000萬日圓（合約台幣2100萬元）高額稅賦...民進黨沒想到如此更名竟然是這樣的下場：被他最信任也最友好的日本政府給坑了。
果然錯誤的政策比貪污可怕，2100萬就這樣打水漂了，還要資助九州水患，核四停建違約賠償金.......夠全國軍公教退休2次.........

http://www.chinatimes.com/newspapers/20170617000318-260118
```

**Comment by MrOrz** [comment]
Frequency: quite a few times a day.
Should boost its priority

<img width="1275" alt="2017-08-11 11 41 15" src="https://user-images.githubusercontent.com/108608/29200706-073fc12e-7e8a-11e7-97e0-732a2fc970d2.png">

**Comment by godgunman** [comment]
https://github.com/cofacts/rumors-line-bot/pull/34
