### ISSUE TITLE
LINE bot 上要怎麼呈現 opinionated replies

### ISSUE THREAD

**Issue by godgunman** [cofacts/rumors-line-bot#32]
主要是因為一次只能回 5 句，但如果一個 article 有 RUMOR 又有 NON-RUMOR 就用掉 4 句了 @@

**Comment by MrOrz** [comment]
當時討論到一半就沒下文惹
http://beta.hackfoldr.org/cofacts/https%253A%252F%252Fhackmd.io%252Fs%252FHJy19V-E-

**Comment by MrOrz** [comment]
記錄一下[這裡的 proposal](https://g0v-tw.slackarchive.io/cofacts/page-16/ts-1505323176000464)：

我覺得這樣的步驟來處理不錯：

1. 如果有真實訊息 reply，就花兩句來列出真實訊息的 reply
2. 如果有不實訊息 reply，就花兩句來列出不實訊息的 reply
3. 如果有個人意見 reply，就花兩句來列出個人意見的 reply。如果句數會超過，那就改成把「N 個回應認為純屬個人意見」放進 `extra` 陣列。
4. 如果有不在查證範圍 reply，就花個兩句來列出不在查證範圍的 reply。如果句數會超過，那就改成把「N 個回應認為不再查證範圍」放進 `extra` 陣列。
5. 如果 `extra` 陣列不為空，那就在最後一句顯示 `有${extra.join('、')}，詳情請見 ${url}`；否則，最後一句放「想要一次看所有回應，請前往：(文章連結)」

簡單來說就是，因為只有 5 句話
所以我們要排個先後順序
能佔用「有 N 個回應含有 OOOO：」+  carousel template 兩句話，只有其中兩種留言
如果超過兩種，剩下的就丟最後一句（第五句）
然後我覺得顯示的優先順序應該是「含有真實訊息」 -> 「含有不實訊息 」-> 「含有個人意見」 -> 「不在查證範圍」

**Comment by MrOrz** [comment]
根據[slack 討論](https://g0v-tw.slackarchive.io/cofacts/page-19/ts-1508089591000033)，讓 LINE bot 像是網站那樣照時間排。

[20171018 決議討論](https://hackmd.io/s/SyzY62ma-)決定的流程：

1. 第1句：有 x 人認為含有不實訊息、y 人認為含有真實訊息，z 人認為含有個人意見。
2. 第2句 (template message)：按照時間排序所有回應，每則回應第一行是「o 含有真實訊息」或「x 含有不實訊息」之類的 (含 emoticon)，然後是回應文字。最後一句的最後一格顯示「看其他回應」。

**Comment by MrOrz** [comment]
Closed via #45
