### ISSUE TITLE
Add article & reply time

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-line-bot#354]
From https://g0v.hackmd.io/NwQhGGgkSvCp6jR-DqB7JQ#Chatbot-%E6%A8%99%E8%A8%98%E8%A8%8A%E6%81%AF%E5%9B%9E%E6%87%89%E6%99%82%E9%96%93

1. 第一句「網路上有人這樣回應這則訊息」加入時間：「網路上有人這樣回應這則 X年 X 月的訊息」
2. 出處前面加上「回應日期：X 年 X 月」
![image](https://github.com/cofacts/rumors-line-bot/assets/108608/9891859a-5229-4aef-b9c5-5d37fb88c98f)

這則訊息首次回報於 X 年 X 月，尚待查核，請先不要相信。以下是 X 年 X 月時機器人初步分析此訊息⋯⋯
如果機器人分析的日期，與回報的日期差不到 30 天，就把「機器人」前的「X年X月時」改成「當時」（現在的新訊息都是如此。會有這個狀況，可能是問到陳年未回訊息，當時還沒有 AI reply）
![image](https://github.com/cofacts/rumors-line-bot/assets/108608/bb34382c-e148-4cb0-841d-12583f7af08c)

**Comment by Jadepypy** [comment]
trying to work on this~

**Comment by jtsaich** [comment]
I'm looking into this

**Comment by jtsaich** [comment]
關於 2. 出處前面加上「回應日期：X 年 X 月」，出處這邊就直接用 Reply.createdAt 嗎？感覺不太用重複聲明如果已經有 1.，因為 Reply.reference 只是一個 string

**Comment by jtsaich** [comment]
<img width="782" alt="Screenshot 2024-01-06 at 2 27 10 PM" src="https://github.com/cofacts/rumors-line-bot/assets/854831/0df4318c-65f5-4dc5-9c93-da982c4d0c27">

<img width="316" alt="Screenshot 2024-01-06 at 2 26 43 PM" src="https://github.com/cofacts/rumors-line-bot/assets/854831/f7f5b101-7578-438e-8f5b-739e4a53a72d">

**Comment by jtsaich** [comment]
<img width="342" alt="Screenshot 2024-01-06 at 2 57 10 PM" src="https://github.com/cofacts/rumors-line-bot/assets/854831/09145449-3e19-4cb9-a519-bc5d8500e85a">
