### ISSUE TITLE
Optimize article selection & reply selection step

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-line-bot#6]
1. Show similarity between the queried document and each article search results, guide users to select the correct article.
2. When similarity is high enough, directly show it to the user. No need for listing.
3. Show the feedback result of the each reply in reply selection step, guide users to select useful replies.
4. When there is only 1 reply available, directly show it to the user. No need for listing.

**Comment by godgunman** [comment]
commits: 
1. 434d61c8
2. f281b1b0
3. bb992d20
4. 8ea02e90
