### ISSUE TITLE
Use flex message to improve the UX of article reason submission

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-line-bot#89]
As discussed in [0725 note](https://hackmd.io/a-_er_PTQ6eSXhdrn9wSDw)

Currently the step that asks the user to submit reason is pretty confusing. Users are facing difficulties in using them and [posts](https://www.facebook.com/groups/cofacts/permalink/2195377860694031/?comment_id=2195479907350493&reply_comment_id=2195674617331022&comment_tracking=%7B%22tn%22%3A%22R3%22%7D) [questions](https://www.facebook.com/groups/cofacts/permalink/2194351154130035/?comment_id=2194496190782198&comment_tracking=%7B%22tn%22%3A%22R2%22%7D) to Facebook as well. We should fix this UX issue ASAP.

### When submitting new article
![submit](https://i.imgur.com/pWBA8TH.png)
Sample: https://gist.github.com/MrOrz/4e8518b28742ec2e2c1e4b87ac759b55

### When confirming the reason
![message & reason](https://i.imgur.com/xCUHw5c.png)
Sample: https://gist.github.com/MrOrz/8ff98577f64d7376302ae0be88041a26

Red text can be even shorter: `若您送出的訊息或理由意味不明、造成闢謠編輯的困擾，未來您將無法送出文章。`

Text colors and margins should be further adjusted to make it look nice.

**Comment by changhc** [comment]
Flex Messages are only supported on LINE iOS/Android versions 6.7.0 and later according to this [doc](https://developers.line.me/en/reference/messaging-api/#flex-message).
